services:
  api-postgres:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    ports:
      - "5432:5432"
    volumes:
      - api-postgres-data:/home/postgres/pgdata/data
    networks:
      - api-network
    restart: always

  api-redis:
    image: redis:latest
    volumes:
      - api-redis-data:/data
    ports:
      - "6378:6379"
    networks:
      - api-network
    restart: always

networks:
  api-network:
    driver: bridge

volumes:
  api-postgres-data:
    driver: local
  api-redis-data:
    driver: local